### ISSUE TITLE
Build failure on Jessie

### ISSUE THREAD

**Issue by dndx** [TheSin-/rpi-img-builder#11]
The build script started failing recently with the following message:

```
mkfs.fat 3.0.27 (2014-11-12)
Loop device does not match a floppy size, using default hd params
Formatting root partition on /dev/loop0...
mke2fs 1.42.12 (29-Aug-2014)
Invalid filesystem option set: none,sparse_super,large_file,filetype,resize_inode,dir_index,ext_attr,has_journal,extent,huge_file,flex_bg,metadata_csum,64bit,dir_nlink,extra_isize
rootfs.mak:176: recipe for target 'Raspbian-jessie-rpix' failed
make[1]: *** [Raspbian-jessie-rpix] Error 1
Makefile:21: recipe for target 'build-rootfs' failed
make: *** [build-rootfs] Error 2
```

I am running Debian Jessie with all packages up to date.

I was able to fix this by manually editing `rootfs/etc/mke2fs.conf` and remove `metadata_csum` from the `ext4` features line, then run `createimg` manually, but it would be great if we can fix this in the build script as well.

Looks like the `mk2fs` Jessie installs is too old to support this new file system option.

**Comment by TheSin-** [comment]
Man this bug is a pain in my butt ;). I keep going back and forth.  I'm going to try and revisit how I do this to be more robust, thanks for letting me know it's back again.

**Comment by karrots** [comment]
Just started using this script. This thread says that updated packages have been applied to the Rasbian mirrors recently. Though I still get the issue.

https://www.raspberrypi.org/forums/viewtopic.php?t=186769&p=1178842

**Comment by TheSin-** [comment]
it's just the options I use when building the image, I'm still trying to find a more sane method to deal with this, I thought taking the defaults for the HOST OS and the defaults from the IMAGE, and crossing them would work but seems something is wrong in that logic that I'm trying to figure out.

**Comment by TheSin-** [comment]
@dndx can you run this and post the results for me please

```
echo $(cat /etc/mke2fs.conf | grep "base_features = " | cut -d "=" -f2 | tr -d '[[:space:]]'),$(cat /etc/mke2fs.conf | grep -A3 "ext4 =" | grep "features = " | cut -d "=" -f2 | tr -d '[[:space:]]')
```

**Comment by TheSin-** [comment]
Believe this is fixed now
