### ISSUE TITLE
Raspberry Pi firmware

### ISSUE THREAD

**Issue by rajil** [TheSin-/rpi-img-builder#15]
Hello,

How can i update the firmware to the latest one (akin to rpi-update) when building the image?

Thanks

**Comment by TheSin-** [comment]
In plugins/disabled there is one called rpi-next, copy it or link it out of the disabled dir and it’ll do ti for you.

https://github.com/TheSin-/rpi-img-builder/tree/master/plugins/disabled/rpi-next

**Comment by TheSin-** [comment]
Did this answer your question? Can this report be closed?
