### ISSUE TITLE
Build failure with LDXE

### ISSUE THREAD

**Issue by rajil** [TheSin-/rpi-img-builder#16]
The postinst for LDXE fails as follows:
```
Running custom postinst scripts
  Running /postinst/LDXE-RZscO
update-alternatives: using /usr/share/libgksu/debian/gconf-defaults.libgksu-sudo to provide /usr/share/gconf/defaults/10_libgksu (libgksu-gconf-defaults) in manual mode
update-alternatives: using /usr/share/raspberrypi-artwork/raspberry-pi-logo.png to provide /usr/share/images/desktop-base/desktop-background (desktop-background) in auto mode
update-alternatives: error: error creating symbolic link '/usr/share/images/desktop-base/desktop-background.dpkg-tmp': No such file or directory
rootfs.mak:108: recipe for target '/home/xx/rpi/rpi-img-builder/rootfs' failed
make[1]: *** [/home/xx/rpi/rpi-img-builder/rootfs] Error 2
Makefile:21: recipe for target 'build-rootfs' failed
make: *** [build-rootfs] Error 2
```

I used the following plugins
```
# cat plugins.txt
plugins/Raspbian/copies-and-fills
plugins/Raspbian/kernel
plugins/Raspbian/rpitools
plugins/Foundation/apt-key
plugins/stretch/extrapackages
plugins/stretch/noPersistentNetGen
plugins/stretch/oldNetNaming
plugins/LDXE
plugins/alsa
plugins/common
plugins/dbreconfig
plugins/disableroot
plugins/extrapackages
plugins/fake-hwclock
plugins/fsckboot
plugins/hostname
plugins/kodi
plugins/mythtvlight
plugins/resizefs
plugins/rpi-next
plugins/sshkeys
plugins/swap
plugins/tmpfs
```

**Comment by TheSin-** [comment]
I NEVER use a GUI on my rpis that is why the LXDE plugin is in disabled.  I assume the package must have changed I got all that from the original raspbian builds, I assume the desktop background file must have moved, do you know where it is now I'll update the plugin.

**Comment by TheSin-** [comment]
Just added desktop-base package to the LXDE package, hopefully that'll fix it.

**Comment by TheSin-** [comment]
did this fix it?  Can this report be closed?

**Comment by rajil** [comment]
Havent tested it yet. I decided not to build LXDE.

**Comment by TheSin-** [comment]
okay no problem lets leave it open then till I get a chance to test it out.

**Comment by TheSin-** [comment]
Looks like omxplayer is broken in the raspbian repo

The following packages have unmet dependencies:
 omxplayer : Depends: libssl1.0.0 but it is not installable
E: Unable to correct problems, you have held broken packages.

Trying to build it with jessie just as test then I'll look into why omxplayer needs a very old out of data ssl

**Comment by TheSin-** [comment]
Builds good now, not sure about running it as I just built the image, but it builds so I'll call it good.

Thanks for the report.
