### ISSUE TITLE
brcmfmac43430-sdio.txt error 404

### ISSUE THREAD

**Issue by adonespitogo** [TheSin-/rpi-img-builder#22]
Hi, thanks for this library.
I can't create an image due to this resource being not found:
```
https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm/brcmfmac43430-sdio.txt
```
I don't know what it does so I don't know how to fix this. Can you explain what is this for and why is it hardcoded in the script?

**Comment by adonespitogo** [comment]
If this doesn't have to be up to date, perhaps we can use the URL of the specific commit instead of pointing to master

**Comment by adonespitogo** [comment]
Fixed by changing the URL to
`https://github.com/RPi-Distro/firmware-nonfree/raw/8d4f3825be09e556c01543119ed50515bd7dd661/brcm/brcmfmac43430-sdio.bin` in `rootfs.mak`

**Comment by TheSin-** [comment]
shoot thanks I'll update this

**Comment by TheSin-** [comment]
thanks for the report, fixed
