### ISSUE TITLE
Quetion: Can this be used to create image for Odroid?

### ISSUE THREAD

**Issue by adonespitogo** [TheSin-/rpi-img-builder#24]
Planning on making custom image for odroid, but I have a very limited knowledge on making custom images. Just want a hint if this is possible and I'll dive into the source code.

**Comment by adonespitogo** [comment]
I've read this thread and I'm thinking it would be cool if I can integrate this into this project. Your project is really helpful and easy to use 

https://forum.odroid.com/viewtopic.php?f=52&t=3662

**Comment by TheSin-** [comment]
I'm sure with a little work it could, but I lost interest in my odroid due to the OLD kernel that was being used, feel free to fork this project and even submit a PR I'd be happy to add support I"m just not interested in doing it myself.
