### ISSUE TITLE
Disable interactivity of hostap plugin

### ISSUE THREAD

**Issue by sgallou** [TheSin-/rpi-img-builder#29]
Hi,

When adding the hostap plugin to my image, at image build time, the script ask to me :

> Configuration file '/etc/default/hostapd'
>  ==> File on system created by you or by a script.
>  ==> File also in package provided by package maintainer.
>    What would you like to do about it ?  Your options are:
>     Y or I  : install the package maintainer's version
>     N or O  : keep your currently-installed version
>       D     : show the differences between the versions
>       Z     : start a shell to examine the situation
>  The default action is to keep your current version.
> *** hostapd (Y/I/N/O/D/Z) [default=N] ?

(I got the same question for '/etc/dnsmasq.conf' file)

As I build my image in a CI environment, this raises errors like 'dpkg: error processing package hostapd (--configure): end of file on stdin at conffile prompt'

Is it a mean to force the answer for these questions ?

Thanks,
sgallou

**Comment by TheSin-** [comment]
it is indeed meant to force them, but a poorly built package can still cause issues.  Let me verify that I didn't miss a call, if you have a plugin that is calling apt-get or dpkg by hand you need to also force it.

**Comment by acsaba1977** [comment]
Hi sgallou,

You can go with the default action.

**Comment by sgallou** [comment]
This [PR](https://github.com/TheSin-/rpi-img-builder/pull/30) works for me.

**Comment by TheSin-** [comment]
PR accepted thank you for fixing this.
