### ISSUE TITLE
Bootfs missing kernel.img, image building completes but unbootable

### ISSUE THREAD

**Issue by emarque** [TheSin-/rpi-img-builder#5]
I've been building images using your solution and it's been amazing for a few months, but in the last week I haven't had success using either the original source or the latest versions. I'm trying to build a relatively clean Raspbian image consisting of a few tweaks to configuration, a heavily modified hostname-init plugin and a custom deb package (of scripts + config files) to run on a rpi3.

I have a successful image saved from my last update about a month ago, and when comparing the boot partitions, it appears that all the bcm27*.dtb, kernel.img and kernel7.img files are missing. The kernel*.img files are what I suspect are causing the rpi to boot into the "rainbow" screen instead of the actual boot sequence.

The entire build sequence stdout is here- I should note that it also asks me about /etc/sysctl.d/98-rpi.conf, saying a version already exists. It waits for user input, which I don't remember it doing before, but I unfortunately don't have a readout of a successful process to compare against.
[imgout.txt](https://github.com/TheSin-/rpi-img-builder/files/572055/imgout.txt)

Hopefully it's something I'm doing wrong/simple fix, but do you have any ideas as to what could be going on?

**Comment by TheSin-** [comment]
the /etc/sysctl.d/98-rpi.conf is because I have it setup in a plugin, and one of the raspbian packages installs it, so is the raspbian packages that is asking, you should answer it with Y, or just remove the plugin version.

if the boot part files are missing then that means the kernel image is either not installing or has changed I'll try to look into it today, can I have you build line options and any plunges you may have enabled/disabled so I can replicate your build?

**Comment by TheSin-** [comment]
yes looks like form the output.txt the image package is not being called I'll track this down, thanks for reporting it.

**Comment by emarque** [comment]
Thanks! My "real" image is missing a bunch of plugins with some changes to plugins kept, but it's the same behavior when using the latest source with no modifications, so I don't think it's got anything to do with the plugin loadout. Let me know if you'd like to see my modified and I'd be happy to send it over. Thanks!

**Comment by TheSin-** [comment]
Looks like I really botched things up for Raspbian on my last update :\

I'm testing building now but I think ```rpi-update raspberrypi-kernel``` is missing from ```plugins/Raspbian/rpitools/packages```

I'll report back soon, thanks for reporting this, as you can see I don't build Raspbian often and as such likely wouldn't have noticed it.

**Comment by TheSin-** [comment]
Looks like the last commit got things sorted here please let me know so I can close the ticket.

**Comment by emarque** [comment]
Yep, it looks like it's working now. I only tried it with the package directly from GH, so I'll try integrating my plugins and building from there, but I suspect it will build just fine now. Thanks, and sorry for the delay in responding- holiday season can get crazy!

**Comment by emarque** [comment]
As an update, I went ahead and packaged all of my various plugins and tried to generate a new image. While it does now result in an image with boot/root partitions, the boot partition is still missing the broadcom stuff and kernel. I noticed you took the raspberrypi-kernel package out of Raspbian/rpitools/packages, but did it end up going somewhere else? I was able to workaround the issue by mounting the boot partition and copying the contents of a known good image.

**Comment by TheSin-** [comment]
yeah it's now in the Raspbian plugins, it is a required package.  And I know it is populating boot with all the request files as I've been building it all morning ;)

So make sure that you are seeing "Raspbian/kernel" in the list of plugins on build

```
Building Raspbian-jessie-rpix_2016-12-15T10:51:46.img
Repositories: Raspbian Foundation
Base repositories: Raspbian
Distribution: jessie
Repository architecture: armhf
System architecture: rpix
Plugins: alsa, common, dbreconfig, disableroot, extrapackages, fake-hwclock, fsckboot, hostname, resizefs, sshkeys, swap, tmpfs, jessie/extrapackages, jessie/noPersistentNetGen, jessie/usbmount, Raspbian/copies-and-fills, Raspbian/kernel, Raspbian/rpitools
```

"Raspbian/kernel" is required here or you get no kernel or boot loader files like dtbs and overlays.

**Comment by emarque** [comment]
Yep, I somehow ended up with an old version of the Raspbian plugin directory. I'm building now, but I'm pretty sure it's going to be fine now. Thanks!

**Comment by TheSin-** [comment]
np, if it isn't report back and I"ll try and help you diagnose it.

**Comment by emarque** [comment]
Sure enough, that set me straight. Thanks again- this tool is awesome!

**Comment by TheSin-** [comment]
np at all, glad it's helping out.
